# Generated by Django 2.0.4 on 2018-04-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='namespace')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('value', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('namespace', 'name', 'value'),
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tagging.Tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tagged item',
                'verbose_name_plural': 'tagged items',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('namespace', 'name', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
    ]
